# config.yaml
bank_loaders:
  amex: "transaction_tracker.loaders.amex.AmexLoader"
  canadiantire: "transaction_tracker.loaders.canadiantire.CanadianTireLoader"

output_modules:
  csv: "transaction_tracker.outputs.csv_output.CSVOutput"
# your merchant→category hints; you can fill these in over time
categories:
  restaurants: []
  groceries: []
  fun: []
  fuel: []