version: '3'

tasks:
  install:
    desc: Install budgify in editable mode
    cmds:
      - pip install -e .

  build:
    desc: Build wheel and source distribution under dist/
    cmds:
      - python -m pip install --upgrade build
      - python -m build

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf build dist *.egg-info

  test:
    desc: Install dependencies and run the test suite
    cmds:
      - pip install -r requirements.txt
      - pytest -vv
