# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjob.proto\x12\x07jobdemo\x1a\x1bgoogle/protobuf/empty.proto\")\n\x03Job\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1b\n\nJobRequest\x12\r\n\x05title\x18\x01 \x01(\t\"(\n\x0bJobResponse\x12\x19\n\x03job\x18\x01 \x01(\x0b\x32\x0c.jobdemo.Job2\xac\x01\n\nJobService\x12\x33\n\x06GetJob\x12\x13.jobdemo.JobRequest\x1a\x14.jobdemo.JobResponse\x12/\n\tCreateJob\x12\x0c.jobdemo.Job\x1a\x14.jobdemo.JobResponse\x12\x38\n\tDeleteJob\x12\x13.jobdemo.JobRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOB']._serialized_start=51
  _globals['_JOB']._serialized_end=92
  _globals['_JOBREQUEST']._serialized_start=94
  _globals['_JOBREQUEST']._serialized_end=121
  _globals['_JOBRESPONSE']._serialized_start=123
  _globals['_JOBRESPONSE']._serialized_end=163
  _globals['_JOBSERVICE']._serialized_start=166
  _globals['_JOBSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
